baseURL = 'https://www.vaines.org/'
languageCode = 'en-gb'
title = 'Vaines.org'
theme = "showfolio"
googleAnalytics = 'G-RLWH268NSH'


[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "Aiden Vaines"

  authorEmail = "aiden@vaines.org"
  authorImage = "/me.png"
  autoDarkMode = true

  copyright = "Copyright © 2022 - Aiden Vaines · All rights reserved"
  favicon = "/favicon.ico"


[params.homepage]
  title = "Hi, I'm Aiden"
  tagline = "A Digital Plumber and Tech Lead"
  # description = "tagline"
  contact = "mailto:aiden@vaines.org"

# [params.homepage.projects]
#   urls = [
#     "https://wallstats.vaines.org",
#     "https://recipe.vaines.org",
#     "https://medium.com/@aidenvaines",
#   ]


[params.homepage.resume]
  username = ""
  pens = []
  skills = [
    "AWS",
    "CI/CD",
    "Python",
    "Tech Leadership",
    "Terraform",
    "VMWare",
  ]


[[params.homepage.resume.work]]
  name = "BJSS"
  role = "Principal Technologist"
  duration = "2019 - Current"

[[params.homepage.resume.work]]
  name = "Oriium Consulting"
  role = "Datacentre Manager"
  duration = "2018 - 2019"

[[params.homepage.resume.work]]
  name = "Univar Ltd"
  role = "Sr. Systems Engineer"
  duration = "2016 - 2018"

[[params.homepage.resume.work]]
  name = "Sleek Networks/Adapt"
  role = "Sr. Hosting Engineer"
  duration = "2014 - 2016"


[[params.homepage.resume.education]]
  name = "BSc Computing Studies (HONS)"
  provider = "University of Huddersfield"
  duration = "2006 - 2009"


[[params.homepage.resume.certifications]]
  name = "Terraform Associate"
  provider = "HashiCorp"
  issued = "2021"

[[params.homepage.resume.certifications]]
  name = "Solutions Architect Associate"
  provider = "Amazon Web Services"
  issued = "2019"

[[params.homepage.resume.certifications]]
  name = "Azure Administrator Associate"
  provider = "Microsoft"
  issued = "2016 - 2009"

[[params.homepage.resume.certifications]]
  name = "VCP5: Data Centre Virtualisation"
  provider = "VMWare"
  issued = "2016 - 2009"


[params.homepage.social]
  twitter = "https://twitter.com/n3rden"
  linkedin = "https://linkedin.com/in/aidenvaines/"
  github = "https://github.com/n3rden"
  medium = "https://medium.com/@aidenvaines"
#   reddit = "https://reddit.com/"
#   dribbble = "https://dribbble.com/"


[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
