baseURL = 'https://www.vaines.org/'
title = ""
theme = "northendlab"
pagination.pagerSize = "5"
summaryLength = "10"

disqusShortname = "vaines-org"
googleAnalytics = "G-RLWH268NSH"
enableRobotsTXT = true

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
unsafe = true

######################### Default Parameters ###########################
[params]
logo = "logo.png"
favicon = "favicon.png"
author = "Aiden Vaines"
description = "A Digital Plumber and Tech Lead"

# homepage main sections
mainSections = ["posts", "talks", "things"]
contact_form_action = "https://formspree.io/f/maykbnjj" # contact form works with : https://formspree.io
copyright = "Copyright © 2025 - Aiden Vaines · All rights reserved"

# search *** true or false (if Search is disable Menu will align in Right) ***
search = true
header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "right" # Sidebar value ("left", "right" or false)

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "G-RLWH268NSH"

######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#5a50e8"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "PT Sans:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"

######################## sidebar widgets #########################
[params.widgets]
sidebar = ["about-me", "featured-post", "social", "subscription"]
# available widget : search,about-me,authors,categories,tags,recent-post,social,promotion,subscription

# preloader
[params.preloader]
enable = false
preloader = "" # use png, jpg, svg or gif format

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2

########################## Plugins ######################################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"

[markup]
[markup.highlight]
style = "igor"

############################## Social Site ##########################
[[params.social]]
icon = "fab fa-linkedin"
link = "https://linkedin.com/in/aidenvaines/"
[[params.social]]
icon = "fab fa-github"
link = "https://github.com/avaines"
[[params.social]]
icon = "fas fa-store"
link = "https://shop.vaines.org"
[[params.social]]
icon = "fab fa-npm"
link = "https://www.npmjs.com/~aiden.vaines"

[languages]
[languages.en]
languageName = "En"
languageCode = "en-gb"
contentDir = "content"
weight = 1

[Languages.en.params.about]
title = "Hi, I'm Aiden"
bio = "I’ve been working in the IT field and filling various roles for the the last 15+ years and I try write up interesting things I've been doing. I am very bad at doing so; but its nice to try get things down every now and then."

[Languages.en.params.banner]
bg_image = "banner-shape.png"
title = "Hi, I'm Aiden Vaines <br> <strong>A Digital Plumber and Tech Lead</strong>"
image = "banner-image.png"

[[Languages.en.menu.main]]
weight = 1
url = "/"
name = "Home"

[[Languages.en.menu.main]]
weight = 2
url = "posts"
name = "Posts"

[[Languages.en.menu.main]]
weight = 3
url = "talks"
name = "Meatspace"

[[Languages.en.menu.main]]
weight = 3
url = "things"
name = "Things I Made"

[[Languages.en.menu.main]]
weight = 4
hasChildren = true
name = "Other"

    [[Languages.en.menu.main]]
    parent = "Other"
    name = "About Me"
    url = "about"
    weight = 1

    [[Languages.en.menu.main]]
    parent = "Other"
    name = "Contact"
    url = "contact"
    weight = 3

    [[Languages.en.menu.main]]
    parent = "Other"
    name = "Cursed Knowledge"
    url = "cursed"
    weight = 2


[[Languages.en.menu.footer]]
weight = 1
url = "about/"
name = "About"

[[Languages.en.menu.footer]]
weight = 2
url = "privacy/"
name = "Privacy"


[[params.social_profile]]
icon = "fab fa-linkedin"
link = "https://linkedin.com/in/aidenvaines/"
[[params.social_profile]]
icon = "fab fa-github"
link = "https://github.com/avaines"
[[params.social_profile]]
icon = "fas fa-store"
link = "https://shop.vaines.org"
[[params.social_profile]]
icon = "fab fa-npm"
link = "https://www.npmjs.com/~aiden.vaines"
